### ISSUE TITLE
Overwrite error when downloading two data instances of one participant with ukb-update

### ISSUE THREAD

**Issue by Hoda1394** [datalad/datalad-ukbiobank#17]
I tried ukb-update to download the bulk data for a participant who has two instances of the same field-id. Data were downloaded successfully but in the end, I received this error: 
[ERROR] File path_to/FreeSurfer/stats/lh.aparc.stats already exists, but new (?) file FreeSurfer/stats/lh.aparc.stats was instructed to be placed there while overwrite=False [add_archive_content.py:__call__:404] (RuntimeError)
 
As I understand, the two instances are downloaded as zip files with different file names but since they were automatically unzipped the content has the same file/folder name and this caused the problem! On the other hand, I want to store both data differently so how should I solve this issue?

**Comment by mih** [comment]
Thx for your report. Such a case has not occurred to me yet. So you get two ZIP for the same data record ID? Or you specific two data record IDs and they give two ZIPs with content that overlaps when extracted?

**Comment by AlexandreHutton** [comment]
This is caused by UKBB naming files the same for session 2 and session 3; the only difference is in the .zip file name (x_20252_2_0.zip vs x_20252_3_0.zip).
The solution is to add in the ses- label to the BIDS directory/file names; the session needs to be identified before the file is unzipped.

**Comment by mih** [comment]
Thx @AlexandreHutton that makes sense. So we would need to inspect the download set of ZIPs, sort them and check whether we have some with the same record ID, and use the trailing counter as a session identifier, such that the content of `x_20252_2_0.zip` ends up in a `ses-2` subdirectory.

**Comment by AlexandreHutton** [comment]
I don't think it's necessary to check that there are multiple sessions; all _2_0 needs the ses-2 label regardless of whether there is a _3_0.zip file. Otherwise, yes; the ukb2bids_map.py filenames also need to be updated to use a session label.

**Comment by mih** [comment]
I am not convinced that we should unconditionally add a session layer. For example, `datalad ukb-init -p 5874415 --record 20227_2_0 20249_2_0` yields a perfectly meaningful single session dataset, even if there would be additional sessions available. I can envision use cases that do not require multi-visit data, or may want to structure multi-visit data using multiple datasets per subject.

**Comment by AlexandreHutton** [comment]
BIDS requires that the session label is added if [at least one subject has multiple sessions](https://bids-specification.readthedocs.io/en/stable/05-longitudinal-and-multi-site-studies.html), though. So if ses-2 is initially downloaded and then ses-3 is requested, it would be necessary to go back and modify all previous files to include the ses- field. Given that subject datasets can't be in the same superset in order to use multiple download connections (#16), I'm not sure it's even possible.

I don't know what to do about the non-BIDS format, though.

**Comment by Hoda1394** [comment]
I was following your discussions and it seems that there is no trick that I can do to fix the problem in the short term. But generally, since UKB is an evolving dataset, it is a better idea to consider future sessions that might be added for one participant.

**Comment by Hoda1394** [comment]
Thank you @mih, I will try it and let you know.

**Comment by Hoda1394** [comment]
@mih,
I could successfully download multiple data instances but there is still an issue!  Downloaded data is separately located in two folders named instance-2 and instance-3  but how about a case when there is another field id that has also has two instances? I suggest putting the field-instance_no. as the folder name to avoid such a problem.

**Comment by mih** [comment]
As far a I understand the docs, the data from one visit/instance does not have naming conflicts. Are you aware of a case that disproves that assumption?

**Comment by Hoda1394** [comment]
I am thinking of a case that has, for example, both brain imaging and eye OCT imaging in two sessions. eye OCT images are also zip files but it has a different field id from brain images. Since all of these data are associated with one participant id it might cause a conflict if eye data also have more than one instance! let me see if I can find a case and see what happens when I try to download data.

**Comment by mih** [comment]
The ZIP files themselves cannot conflict, as they have record IDs and instance IDs in their name. Their extracted content **should** be fine, but if you can find counter-evidence, it would be absolutely instrumental. Thx in advance!
