### ISSUE TITLE
support for data types not downloaded as zip files

### ISSUE THREAD

**Issue by loj** [datalad/datalad-ukbiobank#22]
Some data types (ex: rfmri correlation matrix; field: 25751) are not downloaded as zip files and are rather downloaded as txt files. As a result, these files get left behind in the incoming branch.

**Comment by mih** [comment]
Thx for the report. I'll get to it. Are you aware of a BIDS recommended placement for such data types?

**Comment by loj** [comment]
>  Are you aware of a BIDS recommended placement for such data types?

I'm not aware of one, but I'll look into it.

**Comment by mih** [comment]
Thx @loj!

Also, I ping #23 in case we need to mark such files as `non-bids`.

**Comment by loj** [comment]
I did not find a recommended BIDS placement for these data types, and would say that they belong in `non-bids`.

Suggested mappings:
* '{subj}\_25750\_{session}_0.txt': '{session}/non-bids/fmri/rfmri_full_correlation_matrix_d25.txt'
* '{subj}\_25751\_{session}_0.txt':  '{session}/non-bids/fmri/rfmri_full_correlation_matrix_d100.txt'
* '{subj}\_25752\_{session}_0.txt': '{session}/non-bids/fmri/rfmri_partial_correlation_matrix_d25.txt'
* '{subj}\_25753\_{session}_0.txt': '{session}/non-bids/fmri/rfmri_partial_correlation_matrix_d100.txt'
* '{subj}\_25754\_{session}_0.txt': '{session}/non-bids/fmri/rfmri_component_amplitudes_d25.txt'
* '{subj}\_25755\_{session}_0.txt': '{session}/non-bids/fmri/rfmri_component_amplitudes_d100.txt'

**Comment by mih** [comment]
Sounds good, thx for digging!

**Comment by loj** [comment]
Some additional non-zip data files that should be considered:
* 25747_2_0.adv (Eprime advisor file tfmri)
* 25748_2_0.txt (Eprime text file tfmri)
* 25749_2_0.ed2 (Eprime ed2 file tfmri)

Suggested mappings:

* '{subj}\_25747\_{session}_0.adv': '{session}/non-bids/fmri/tfmri_eprime.adv'
* '{subj}\_25748\_{session}_0.txt': '{session}/non-bids/fmri/tfmri_eprime.txt'
* '{subj}\_25749\_{session}_0.ed2': '{session}/non-bids/fmri/tfmri_eprime.ed2'

**Comment by mih** [comment]
I verified that https://github.com/datalad/datalad-ukbiobank/pull/28 can handle .adv, .txt and .ed2 files.
