### ISSUE TITLE
creating datalad-ukb dataset in a non empty directory

### ISSUE THREAD

**Issue by djarecka** [datalad/datalad-ukbiobank#26]
Could you give me some advice how to create `datalad-ukb` dataset from already downloaded data? I can create datalad dataset and add the files, I can also run `ukb-init` and `ukb-update`, but I believe `ukb-update` doesn't recognize existing files and just downloads everything again. Am I right?

**Comment by loj** [comment]
Hey, I'm in a similar-ish situation, and what I did was swap out the `ukbfetch` tool with a script that parses the `.ukbbatch` file and simply copies the zip files you've already downloaded from wherever you have them stored.

Here's my faux `ukbfetch`:
```                                                                          
#!/bin/bash

set -e

for line in $(cat .ukbbatch |  sed 's/ /,/g'); do
    sub_id=${line%,*}
    modality=${line#*,}

    # transfer data from remote server
    rsync -avh --progress me@remote.server.de:"/ukbiobank/zip_files/${sub_id}_${modality}*" ./

done
```
With this you can run `ukb-init` and `ukb-update` the same as before.

I hope that helps! :-)

**Comment by mih** [comment]
@djarecka  Does that work for you?

**Comment by djarecka** [comment]
sorry for late answer, will check check it tomorrow!

**Comment by djarecka** [comment]
@loj - sorry that it took me so long, started working on something else, and forgot..

I've tried to use your trick today, but I've never really worked with ukb datasets and I'm missing some important pieces. where/what is `.ukbbatch`, I was checking the project directory and website and couldn't find it. 
Also, do you have a way to point datalad to your `ukbfetch` bash script or you have to completely overwrite `ukbfetch` command.

**Comment by loj** [comment]
@djarecka - no worries. :-) I hope my answers to your questions make sense. If not, let me know. :-)

> where/what is .ukbbatch

`.ukbbatch` is created by `datalad ukb-init` and lives in the `incoming` branch of the dataset. It contains the participant id and data record ids. 

`datalad ukb-update` calls the `ukbfetch` tool, which accepts a batch file (`.ukbbatch` in this case) as an argument to download multiple subjects at once.

Here's an example `.ukbbatch` file:
```
1000201 20227_2_0
1000201 20249_2_0
1000201 20250_2_0
1000201 20251_2_0
1000201 20252_2_0
1000201 20253_2_0
```

> do you have a way to point datalad to your ukbfetch bash script or you have to completely overwrite ukbfetch command.

I move the `ukbfetch` tool elsewhere and replace it with my bash script, which I name `ukbfetch`. This allows `datalad ukb-update` to function in the same way, but it "fetches" the data from our remote server rather than from the UKB.

**Comment by djarecka** [comment]
Thank you so much for clarifications! Planning to try it tomorrow !

**Comment by djarecka** [comment]
ok, found `.ukbbatch` and added my script for `ukbfetch`, but just wanna be sure that I'm not missing anything - I still have to ask `datalad` to save the files I copy? it doesn't do it automatically when running `datalad ukb-update`. Is that right?

**Comment by loj** [comment]
> I still have to ask datalad to save the files I copy? it doesn't do it automatically when running datalad ukb-update. Is that right?

This should be handled by `ukb-update`. It calls your `ukbfetch` script with `datalad run`, and should save the files you copy with a commit message of "Update from UKbiobank".

**Comment by djarecka** [comment]
which version of datalad and datald-ukb you are using?

**Comment by loj** [comment]
I've been using several different versions, but right now I'm using datalad 0.13.0rc2 and datalad-ukbiobank 0.2. Were you just curious or are you running into problems with `ukb-update`?

If you're running into problems, let me know. I'm happy to help. :-)

**Comment by mih** [comment]
I will close this now. There is not much that could be added to the description that @loj gave above. Feel free to open open another issue, if there are specific problems with this approach.

**Comment by djarecka** [comment]
ok, thank you. Sorry, I'm slow with this... I was  still having issue with `datalad ukb-update` not saving the files after using `rsync` in the `ukbfetch` script. But it looks like @satra was also working on the ukb data management, so waiting to see what is his workflow to deal with the data.
