### ISSUE TITLE
Juelich / Montreal UKB project todo list

### ISSUE THREAD

**Issue by jbpoline** [datalad/datalad-ukbiobank#53]
# @jb : Get the mapping 
- Send email to Alan Simon (cc Laura)

# fmriprep reproducibility
	- @jb : talk to Basile for LTS : is that fixing FS / ANTS etc reproducibility?
	- timeline 

# Mtl : Distrubting computing 

#

**Comment by jb** [comment]
https://giphy.com/gifs/fire-forums-arts-134vVkHV9wQtaw

**Comment by mih** [comment]
Closing this old draft.
