### ISSUE TITLE
hardlink issue with datalad, datalad-ukbiobank (likely a git-annex issue)

### ISSUE THREAD

**Issue by satra** [datalad/datalad-ukbiobank#57]
this may be more directly a git-annex issue but i will post it here first:

for our ukbiobank processing i've written a wrapper that either hardlinks to a local file in some other directory or fetches it remotely. however this fails in some local filemode modification step because it's a hardlink.

the hardlink would allow us to not duplicate 100+TB and allow us to remove things after everything is taken care of.

```
$ datalad ukb-update -k keyfile
[INFO   ] == Command start (output follows) ===== 
Found: linking to local file
... repeat for all files
[INFO   ] == Command exit (modification check follows) =====                                                                                        
[ERROR  ]   2196131_21011_0_0.fda: setFileMode: permission denied (Operation not permitted) [add(/om4/project/biobank/testukb/2196131_21011_0_0.fda)] 
... repeats for all files
```

**Comment by mih** [comment]
For the same reason that you cite, git-annex reuses the same link and moves it to the key store. It then removes write permissions. This is the intended behavior, and not a bug.

Maybe you want to experiment with initializing the repo with `--shared=group` or even more open. That removes all protection, but I dont think you are looking for standard git-annex behavior.

**Comment by mih** [comment]
@yarikoptic AFAICS this has little to do with ukbiobank. It seems as if it is a save call that is failing. @satra Can you run with `--log-level=debug` for a bit more insight.

**Comment by yarikoptic** [comment]
oh, if so -- feel welcome to transfer it back to datalad -- I was just trying to minimize the scary number of open issues

**Comment by satra** [comment]
@mih - we will try the next time we get there. we are still trying to figure out our best ukb approach for creation and update. i will close for now.
